[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "colabdesign"
version = "1.4"
description = "Making Protein Design accessible to all via Google Colab!"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Sergey Ovchinnikov", email = "sokrypton@gmail.com"},
    {name = "Shihao Feng"},
    {name = "Justas Dauparas"},
    {name = "Weikun Wu"},
    {name = "Christopher Frank"},
]
maintainers = [
    {name = "Sergey Ovchinnikov", email = "sokrypton@gmail.com"},
]
keywords = [
    "protein design",
    "alphafold",
    "colabdesign",
    "computational biology",
    "bioinformatics",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "py3Dmol",
    "absl-py",
    "biopython",
    "chex",
    "dm-haiku",
    "dm-tree",
    "immutabledict",
    "ml-collections",
    "numpy",
    "pandas",
    "scipy",
    "optax",
    "joblib",
    "matplotlib",
    "IPython",
    "jax[cuda12]==0.5.3; sys_platform == 'linux'",
    "pyarrow",
    "typer",
    "jax==0.5.3",
    "jax-cuda12-plugin==0.5.3",
    "jax-cuda12-pjrt==0.5.3",
    "click==8.1.7",

#    # minimal safety pins
#    "nvidia-cublas-cu12<12.9",     # avoid 12.9+ with jax 0.5.3
#    "nvidia-cudnn-cu12<9.11",      # avoid 9.11+ with JAX 0.5.3
#
    # Keep the core CUDA bits aligned with 12.8.x (broad, not exact)
    "nvidia-cuda-runtime-cu12>=12.8,<12.9",
    "nvidia-cuda-nvrtc-cu12>=12.8,<12.9",
    "nvidia-nvjitlink-cu12>=12.8,<12.9",

    # CUDA 12.8 user-space libs (match what worked on H100)
    "nvidia-cuda-runtime-cu12==12.8.*",
    "nvidia-cuda-nvrtc-cu12==12.8.*",
    "nvidia-cuda-cupti-cu12==12.8.*",
    "nvidia-nvjitlink-cu12==12.8.*",
    "nvidia-cublas-cu12==12.8.*",
    "nvidia-cufft-cu12==11.2.*",
    "nvidia-curand-cu12==10.3.*",
    "nvidia-cusolver-cu12==11.6.*",
    "nvidia-cusparse-cu12==12.4.*",
    "nvidia-nccl-cu12==2.20.*",
    "nvidia-cudnn-cu12==9.1.*",
]

[project.urls]
Homepage = "https://github.com/sokrypton/ColabDesign"
Repository = "https://github.com/sokrypton/ColabDesign"
Documentation = "https://github.com/sokrypton/ColabDesign"
"Bug Tracker" = "https://github.com/sokrypton/ColabDesign/issues"
Discord = "https://discord.gg/gna8maru7d"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["colabdesign*"]

